name: Ejecutar predicción cada hora

on:
  schedule:
    #- cron:  '0 * * * *'     # cada hora, hora UTC
  workflow_dispatch:         # permite ejecutarlo manualmente desde GitHub

jobs:
  cron_predict:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar el repo
        uses: actions/checkout@v4

      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ejecutar predicción
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
       # run: python cron_predict.py
